services:
  worldcup-simulator:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - worldcup-stats
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  worldcup-stats:
    build:
      context: .
      dockerfile: Dockerfile.stats
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
