services:
  worldcup-simulator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  worldcup-stats:
    build:
      context: .
      dockerfile: Dockerfile.stats
    ports:
      - "90:90"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
