export const FALLBACK_MATCHES = [
  {
    "id": 1,
    "date": "2026-06-11",
    "time": "13:00",
    "group": "A",
    "stadium": "Estadio Azteca",
    "city": "Mexico City",
    "country": "Mexico",
    "home_team": "Mexico",
    "away_team": "South Africa",
    "score": "2-0",
    "status": "finished"
  },
  {
    "id": 2,
    "date": "2026-06-11",
    "time": "20:00",
    "group": "A",
    "stadium": "Estadio Akron",
    "city": "Guadalajara",
    "country": "Mexico",
    "home_team": "South Korea",
    "away_team": "Czech Republic",
    "score": "2-1",
    "status": "finished"
  },
  {
    "id": 3,
    "date": "2026-06-12",
    "time": "15:00",
    "group": "B",
    "stadium": "BMO Field",
    "city": "Toronto",
    "country": "Canada",
    "home_team": "Canada",
    "away_team": "Bosnia and Herzegovina",
    "score": "1-1",
    "status": "finished"
  },
  {
    "id": 4,
    "date": "2026-06-12",
    "time": "18:00",
    "group": "D",
    "stadium": "SoFi Stadium",
    "city": "Los Angeles",
    "country": "USA",
    "home_team": "USA",
    "away_team": "Paraguay",
    "score": "4-1",
    "status": "finished"
  },
  {
    "id": 5,
    "date": "2026-06-13",
    "time": "12:00",
    "group": "B",
    "stadium": "Levi's Stadium",
    "city": "Santa Clara",
    "country": "USA",
    "home_team": "Qatar",
    "away_team": "Switzerland",
    "score": "1-1",
    "status": "finished"
  },
  {
    "id": 6,
    "date": "2026-06-13",
    "time": "18:00",
    "group": "C",
    "stadium": "MetLife Stadium",
    "city": "East Rutherford",
    "country": "USA",
    "home_team": "Brazil",
    "away_team": "Morocco",
    "score": "1-1",
    "status": "finished"
  },
  {
    "id": 7,
    "date": "2026-06-13",
    "time": "21:00",
    "group": "C",
    "stadium": "Gillette Stadium",
    "city": "Boston",
    "country": "USA",
    "home_team": "Haiti",
    "away_team": "Scotland",
    "score": "0-1",
    "status": "finished"
  },
  {
    "id": 8,
    "date": "2026-06-13",
    "time": "21:00",
    "group": "D",
    "stadium": "BC Place",
    "city": "Vancouver",
    "country": "Canada",
    "home_team": "Australia",
    "away_team": "Turkey",
    "score": "2-0",
    "status": "finished"
  },
  {
    "id": 9,
    "date": "2026-06-14",
    "time": "12:00",
    "group": "E",
    "stadium": "NRG Stadium",
    "city": "Houston",
    "country": "USA",
    "home_team": "Germany",
    "away_team": "Curaçao",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 10,
    "date": "2026-06-14",
    "time": "19:00",
    "group": "E",
    "stadium": "Lincoln Financial Field",
    "city": "Philadelphia",
    "country": "USA",
    "home_team": "Ivory Coast",
    "away_team": "Ecuador",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 11,
    "date": "2026-06-14",
    "time": "15:00",
    "group": "F",
    "stadium": "AT&T Stadium",
    "city": "Dallas",
    "country": "USA",
    "home_team": "Netherlands",
    "away_team": "Japan",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 12,
    "date": "2026-06-14",
    "time": "20:00",
    "group": "F",
    "stadium": "Estadio BBVA",
    "city": "Monterrey",
    "country": "Mexico",
    "home_team": "Sweden",
    "away_team": "Tunisia",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 13,
    "date": "2026-06-15",
    "time": "12:00",
    "group": "H",
    "stadium": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "country": "USA",
    "home_team": "Spain",
    "away_team": "Cape Verde",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 14,
    "date": "2026-06-15",
    "time": "18:00",
    "group": "H",
    "stadium": "Hard Rock Stadium",
    "city": "Miami",
    "country": "USA",
    "home_team": "Saudi Arabia",
    "away_team": "Uruguay",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 15,
    "date": "2026-06-15",
    "time": "12:00",
    "group": "G",
    "stadium": "Lumen Field",
    "city": "Seattle",
    "country": "USA",
    "home_team": "Belgium",
    "away_team": "Egypt",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 16,
    "date": "2026-06-15",
    "time": "18:00",
    "group": "G",
    "stadium": "SoFi Stadium",
    "city": "Los Angeles",
    "country": "USA",
    "home_team": "Iran",
    "away_team": "New Zealand",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 17,
    "date": "2026-06-16",
    "time": "21:00",
    "group": "J",
    "stadium": "Levi's Stadium",
    "city": "Santa Clara",
    "country": "USA",
    "home_team": "Austria",
    "away_team": "Jordan",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 18,
    "date": "2026-06-16",
    "time": "15:00",
    "group": "I",
    "stadium": "MetLife Stadium",
    "city": "East Rutherford",
    "country": "USA",
    "home_team": "France",
    "away_team": "Senegal",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 19,
    "date": "2026-06-16",
    "time": "18:00",
    "group": "I",
    "stadium": "Gillette Stadium",
    "city": "Boston",
    "country": "USA",
    "home_team": "Iraq",
    "away_team": "Norway",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 20,
    "date": "2026-06-16",
    "time": "20:00",
    "group": "J",
    "stadium": "Arrowhead Stadium",
    "city": "Kansas City",
    "country": "USA",
    "home_team": "Argentina",
    "away_team": "Algeria",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 21,
    "date": "2026-06-17",
    "time": "12:00",
    "group": "K",
    "stadium": "NRG Stadium",
    "city": "Houston",
    "country": "USA",
    "home_team": "Portugal",
    "away_team": "DR Congo",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 22,
    "date": "2026-06-17",
    "time": "15:00",
    "group": "L",
    "stadium": "AT&T Stadium",
    "city": "Dallas",
    "country": "USA",
    "home_team": "England",
    "away_team": "Croatia",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 23,
    "date": "2026-06-17",
    "time": "19:00",
    "group": "L",
    "stadium": "BMO Field",
    "city": "Toronto",
    "country": "Canada",
    "home_team": "Ghana",
    "away_team": "Panama",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 24,
    "date": "2026-06-17",
    "time": "20:00",
    "group": "K",
    "stadium": "Estadio Azteca",
    "city": "Mexico City",
    "country": "Mexico",
    "home_team": "Uzbekistan",
    "away_team": "Colombia",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 25,
    "date": "2026-06-18",
    "time": "12:00",
    "group": "A",
    "stadium": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "country": "USA",
    "home_team": "Czech Republic",
    "away_team": "South Africa",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 26,
    "date": "2026-06-18",
    "time": "12:00",
    "group": "B",
    "stadium": "SoFi Stadium",
    "city": "Los Angeles",
    "country": "USA",
    "home_team": "Switzerland",
    "away_team": "Bosnia and Herzegovina",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 27,
    "date": "2026-06-18",
    "time": "15:00",
    "group": "B",
    "stadium": "BC Place",
    "city": "Vancouver",
    "country": "Canada",
    "home_team": "Canada",
    "away_team": "Qatar",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 28,
    "date": "2026-06-18",
    "time": "19:00",
    "group": "A",
    "stadium": "Estadio Akron",
    "city": "Guadalajara",
    "country": "Mexico",
    "home_team": "Mexico",
    "away_team": "South Korea",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 29,
    "date": "2026-06-19",
    "time": "20:00",
    "group": "D",
    "stadium": "Levi's Stadium",
    "city": "Santa Clara",
    "country": "USA",
    "home_team": "Turkey",
    "away_team": "Paraguay",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 30,
    "date": "2026-06-19",
    "time": "12:00",
    "group": "D",
    "stadium": "Lumen Field",
    "city": "Seattle",
    "country": "USA",
    "home_team": "USA",
    "away_team": "Australia",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 31,
    "date": "2026-06-19",
    "time": "18:00",
    "group": "C",
    "stadium": "Gillette Stadium",
    "city": "Boston",
    "country": "USA",
    "home_team": "Scotland",
    "away_team": "Morocco",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 32,
    "date": "2026-06-19",
    "time": "20:30",
    "group": "C",
    "stadium": "Lincoln Financial Field",
    "city": "Philadelphia",
    "country": "USA",
    "home_team": "Brazil",
    "away_team": "Haiti",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 33,
    "date": "2026-06-20",
    "time": "20:00",
    "group": "F",
    "stadium": "Estadio BBVA",
    "city": "Monterrey",
    "country": "Mexico",
    "home_team": "Tunisia",
    "away_team": "Japan",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 34,
    "date": "2026-06-20",
    "time": "12:00",
    "group": "F",
    "stadium": "NRG Stadium",
    "city": "Houston",
    "country": "USA",
    "home_team": "Netherlands",
    "away_team": "Sweden",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 35,
    "date": "2026-06-20",
    "time": "16:00",
    "group": "E",
    "stadium": "BMO Field",
    "city": "Toronto",
    "country": "Canada",
    "home_team": "Germany",
    "away_team": "Ivory Coast",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 36,
    "date": "2026-06-20",
    "time": "19:00",
    "group": "E",
    "stadium": "Arrowhead Stadium",
    "city": "Kansas City",
    "country": "USA",
    "home_team": "Ecuador",
    "away_team": "Curaçao",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 37,
    "date": "2026-06-21",
    "time": "12:00",
    "group": "H",
    "stadium": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "country": "USA",
    "home_team": "Spain",
    "away_team": "Saudi Arabia",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 38,
    "date": "2026-06-21",
    "time": "12:00",
    "group": "G",
    "stadium": "SoFi Stadium",
    "city": "Los Angeles",
    "country": "USA",
    "home_team": "Belgium",
    "away_team": "Iran",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 39,
    "date": "2026-06-21",
    "time": "18:00",
    "group": "H",
    "stadium": "Hard Rock Stadium",
    "city": "Miami",
    "country": "USA",
    "home_team": "Uruguay",
    "away_team": "Cape Verde",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 40,
    "date": "2026-06-21",
    "time": "18:00",
    "group": "G",
    "stadium": "BC Place",
    "city": "Vancouver",
    "country": "Canada",
    "home_team": "New Zealand",
    "away_team": "Egypt",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 41,
    "date": "2026-06-22",
    "time": "12:00",
    "group": "J",
    "stadium": "AT&T Stadium",
    "city": "Dallas",
    "country": "USA",
    "home_team": "Argentina",
    "away_team": "Austria",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 42,
    "date": "2026-06-22",
    "time": "17:00",
    "group": "I",
    "stadium": "Lincoln Financial Field",
    "city": "Philadelphia",
    "country": "USA",
    "home_team": "France",
    "away_team": "Iraq",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 43,
    "date": "2026-06-22",
    "time": "20:00",
    "group": "I",
    "stadium": "MetLife Stadium",
    "city": "East Rutherford",
    "country": "USA",
    "home_team": "Norway",
    "away_team": "Senegal",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 44,
    "date": "2026-06-22",
    "time": "20:00",
    "group": "J",
    "stadium": "Levi's Stadium",
    "city": "Santa Clara",
    "country": "USA",
    "home_team": "Jordan",
    "away_team": "Algeria",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 45,
    "date": "2026-06-23",
    "time": "12:00",
    "group": "K",
    "stadium": "NRG Stadium",
    "city": "Houston",
    "country": "USA",
    "home_team": "Portugal",
    "away_team": "Uzbekistan",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 46,
    "date": "2026-06-23",
    "time": "16:00",
    "group": "L",
    "stadium": "Gillette Stadium",
    "city": "Boston",
    "country": "USA",
    "home_team": "England",
    "away_team": "Ghana",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 47,
    "date": "2026-06-23",
    "time": "19:00",
    "group": "L",
    "stadium": "BMO Field",
    "city": "Toronto",
    "country": "Canada",
    "home_team": "Panama",
    "away_team": "Croatia",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 48,
    "date": "2026-06-23",
    "time": "20:00",
    "group": "K",
    "stadium": "Estadio Akron",
    "city": "Guadalajara",
    "country": "Mexico",
    "home_team": "Colombia",
    "away_team": "DR Congo",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 49,
    "date": "2026-06-24",
    "time": "12:00",
    "group": "B",
    "stadium": "BC Place",
    "city": "Vancouver",
    "country": "Canada",
    "home_team": "Switzerland",
    "away_team": "Canada",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 50,
    "date": "2026-06-24",
    "time": "12:00",
    "group": "B",
    "stadium": "Lumen Field",
    "city": "Seattle",
    "country": "USA",
    "home_team": "Bosnia and Herzegovina",
    "away_team": "Qatar",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 51,
    "date": "2026-06-24",
    "time": "18:00",
    "group": "C",
    "stadium": "Hard Rock Stadium",
    "city": "Miami",
    "country": "USA",
    "home_team": "Scotland",
    "away_team": "Brazil",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 52,
    "date": "2026-06-24",
    "time": "18:00",
    "group": "C",
    "stadium": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "country": "USA",
    "home_team": "Morocco",
    "away_team": "Haiti",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 53,
    "date": "2026-06-24",
    "time": "19:00",
    "group": "A",
    "stadium": "Estadio Azteca",
    "city": "Mexico City",
    "country": "Mexico",
    "home_team": "Czech Republic",
    "away_team": "Mexico",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 54,
    "date": "2026-06-24",
    "time": "19:00",
    "group": "A",
    "stadium": "Estadio BBVA",
    "city": "Monterrey",
    "country": "Mexico",
    "home_team": "South Africa",
    "away_team": "South Korea",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 55,
    "date": "2026-06-25",
    "time": "16:00",
    "group": "E",
    "stadium": "MetLife Stadium",
    "city": "East Rutherford",
    "country": "USA",
    "home_team": "Ecuador",
    "away_team": "Germany",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 56,
    "date": "2026-06-25",
    "time": "16:00",
    "group": "E",
    "stadium": "Lincoln Financial Field",
    "city": "Philadelphia",
    "country": "USA",
    "home_team": "Curaçao",
    "away_team": "Ivory Coast",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 57,
    "date": "2026-06-25",
    "time": "18:00",
    "group": "F",
    "stadium": "AT&T Stadium",
    "city": "Dallas",
    "country": "USA",
    "home_team": "Japan",
    "away_team": "Sweden",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 58,
    "date": "2026-06-25",
    "time": "18:00",
    "group": "F",
    "stadium": "Arrowhead Stadium",
    "city": "Kansas City",
    "country": "USA",
    "home_team": "Tunisia",
    "away_team": "Netherlands",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 59,
    "date": "2026-06-25",
    "time": "19:00",
    "group": "D",
    "stadium": "SoFi Stadium",
    "city": "Los Angeles",
    "country": "USA",
    "home_team": "Turkey",
    "away_team": "USA",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 60,
    "date": "2026-06-25",
    "time": "19:00",
    "group": "D",
    "stadium": "Levi's Stadium",
    "city": "Santa Clara",
    "country": "USA",
    "home_team": "Paraguay",
    "away_team": "Australia",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 61,
    "date": "2026-06-26",
    "time": "15:00",
    "group": "I",
    "stadium": "Gillette Stadium",
    "city": "Boston",
    "country": "USA",
    "home_team": "Norway",
    "away_team": "France",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 62,
    "date": "2026-06-26",
    "time": "15:00",
    "group": "I",
    "stadium": "BMO Field",
    "city": "Toronto",
    "country": "Canada",
    "home_team": "Senegal",
    "away_team": "Iraq",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 63,
    "date": "2026-06-26",
    "time": "19:00",
    "group": "H",
    "stadium": "NRG Stadium",
    "city": "Houston",
    "country": "USA",
    "home_team": "Cape Verde",
    "away_team": "Saudi Arabia",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 64,
    "date": "2026-06-26",
    "time": "18:00",
    "group": "H",
    "stadium": "Estadio Akron",
    "city": "Guadalajara",
    "country": "Mexico",
    "home_team": "Uruguay",
    "away_team": "Spain",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 65,
    "date": "2026-06-26",
    "time": "20:00",
    "group": "G",
    "stadium": "Lumen Field",
    "city": "Seattle",
    "country": "USA",
    "home_team": "Egypt",
    "away_team": "Iran",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 66,
    "date": "2026-06-26",
    "time": "20:00",
    "group": "G",
    "stadium": "BC Place",
    "city": "Vancouver",
    "country": "Canada",
    "home_team": "New Zealand",
    "away_team": "Belgium",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 67,
    "date": "2026-06-27",
    "time": "17:00",
    "group": "L",
    "stadium": "MetLife Stadium",
    "city": "East Rutherford",
    "country": "USA",
    "home_team": "Panama",
    "away_team": "England",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 68,
    "date": "2026-06-27",
    "time": "17:00",
    "group": "L",
    "stadium": "Lincoln Financial Field",
    "city": "Philadelphia",
    "country": "USA",
    "home_team": "Croatia",
    "away_team": "Ghana",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 69,
    "date": "2026-06-27",
    "time": "19:30",
    "group": "K",
    "stadium": "Hard Rock Stadium",
    "city": "Miami",
    "country": "USA",
    "home_team": "Colombia",
    "away_team": "Portugal",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 70,
    "date": "2026-06-27",
    "time": "19:30",
    "group": "K",
    "stadium": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "country": "USA",
    "home_team": "DR Congo",
    "away_team": "Uzbekistan",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 71,
    "date": "2026-06-27",
    "time": "21:00",
    "group": "J",
    "stadium": "Arrowhead Stadium",
    "city": "Kansas City",
    "country": "USA",
    "home_team": "Algeria",
    "away_team": "Austria",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 72,
    "date": "2026-06-27",
    "time": "21:00",
    "group": "J",
    "stadium": "AT&T Stadium",
    "city": "Dallas",
    "country": "USA",
    "home_team": "Jordan",
    "away_team": "Argentina",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 73,
    "date": "2026-06-28",
    "time": "TBD",
    "group": "32 avos de final",
    "stadium": "SoFi Stadium",
    "city": "Los Angeles",
    "country": "USA",
    "home_team": "2nd Group A",
    "away_team": "2nd Group B",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 74,
    "date": "2026-06-29",
    "time": "TBD",
    "group": "32 avos de final",
    "stadium": "Gillette Stadium",
    "city": "Boston",
    "country": "USA",
    "home_team": "Winner Group E",
    "away_team": "3rd A/B/C/D/F",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 75,
    "date": "2026-06-29",
    "time": "TBD",
    "group": "32 avos de final",
    "stadium": "Estadio BBVA",
    "city": "Monterrey",
    "country": "Mexico",
    "home_team": "Winner Group F",
    "away_team": "2nd Group C",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 76,
    "date": "2026-06-29",
    "time": "TBD",
    "group": "32 avos de final",
    "stadium": "NRG Stadium",
    "city": "Houston",
    "country": "USA",
    "home_team": "Winner Group C",
    "away_team": "2nd Group F",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 77,
    "date": "2026-06-30",
    "time": "TBD",
    "group": "32 avos de final",
    "stadium": "MetLife Stadium",
    "city": "East Rutherford",
    "country": "USA",
    "home_team": "Winner Group I",
    "away_team": "3rd C/D/F/G/H",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 78,
    "date": "2026-06-30",
    "time": "TBD",
    "group": "32 avos de final",
    "stadium": "AT&T Stadium",
    "city": "Dallas",
    "country": "USA",
    "home_team": "2nd Group E",
    "away_team": "2nd Group I",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 79,
    "date": "2026-06-30",
    "time": "TBD",
    "group": "32 avos de final",
    "stadium": "Estadio Azteca",
    "city": "Mexico City",
    "country": "Mexico",
    "home_team": "Winner Group A",
    "away_team": "3rd C/E/F/H/I",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 80,
    "date": "2026-07-01",
    "time": "TBD",
    "group": "32 avos de final",
    "stadium": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "country": "USA",
    "home_team": "Winner Group L",
    "away_team": "3rd E/H/I/J/K",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 81,
    "date": "2026-07-01",
    "time": "TBD",
    "group": "32 avos de final",
    "stadium": "Levi's Stadium",
    "city": "Santa Clara",
    "country": "USA",
    "home_team": "Winner Group D",
    "away_team": "3rd B/E/F/I/J",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 82,
    "date": "2026-07-01",
    "time": "TBD",
    "group": "32 avos de final",
    "stadium": "Lumen Field",
    "city": "Seattle",
    "country": "USA",
    "home_team": "Winner Group G",
    "away_team": "3rd A/E/H/I/J",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 83,
    "date": "2026-07-02",
    "time": "TBD",
    "group": "32 avos de final",
    "stadium": "BMO Field",
    "city": "Toronto",
    "country": "Canada",
    "home_team": "2nd Group K",
    "away_team": "2nd Group L",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 84,
    "date": "2026-07-02",
    "time": "TBD",
    "group": "32 avos de final",
    "stadium": "SoFi Stadium",
    "city": "Los Angeles",
    "country": "USA",
    "home_team": "Winner Group H",
    "away_team": "2nd Group J",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 85,
    "date": "2026-07-02",
    "time": "TBD",
    "group": "32 avos de final",
    "stadium": "BC Place",
    "city": "Vancouver",
    "country": "Canada",
    "home_team": "Winner Group B",
    "away_team": "3rd E/F/G/I/J",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 86,
    "date": "2026-07-03",
    "time": "TBD",
    "group": "32 avos de final",
    "stadium": "Hard Rock Stadium",
    "city": "Miami",
    "country": "USA",
    "home_team": "Winner Group J",
    "away_team": "2nd Group H",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 87,
    "date": "2026-07-03",
    "time": "TBD",
    "group": "32 avos de final",
    "stadium": "Arrowhead Stadium",
    "city": "Kansas City",
    "country": "USA",
    "home_team": "Winner Group K",
    "away_team": "3rd D/E/I/J/L",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 88,
    "date": "2026-07-03",
    "time": "TBD",
    "group": "32 avos de final",
    "stadium": "AT&T Stadium",
    "city": "Dallas",
    "country": "USA",
    "home_team": "2nd Group D",
    "away_team": "2nd Group G",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 89,
    "date": "2026-07-04",
    "time": "TBD",
    "group": "Oitavas de final",
    "stadium": "Lincoln Financial Field",
    "city": "Philadelphia",
    "country": "USA",
    "home_team": "Winner Match 74",
    "away_team": "Winner Match 77",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 90,
    "date": "2026-07-04",
    "time": "TBD",
    "group": "Oitavas de final",
    "stadium": "NRG Stadium",
    "city": "Houston",
    "country": "USA",
    "home_team": "Winner Match 73",
    "away_team": "Winner Match 75",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 91,
    "date": "2026-07-05",
    "time": "TBD",
    "group": "Oitavas de final",
    "stadium": "MetLife Stadium",
    "city": "East Rutherford",
    "country": "USA",
    "home_team": "Winner Match 76",
    "away_team": "Winner Match 78",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 92,
    "date": "2026-07-05",
    "time": "TBD",
    "group": "Oitavas de final",
    "stadium": "Estadio Azteca",
    "city": "Mexico City",
    "country": "Mexico",
    "home_team": "Winner Match 79",
    "away_team": "Winner Match 80",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 93,
    "date": "2026-07-06",
    "time": "TBD",
    "group": "Oitavas de final",
    "stadium": "AT&T Stadium",
    "city": "Dallas",
    "country": "USA",
    "home_team": "Winner Match 83",
    "away_team": "Winner Match 84",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 94,
    "date": "2026-07-06",
    "time": "TBD",
    "group": "Oitavas de final",
    "stadium": "Lumen Field",
    "city": "Seattle",
    "country": "USA",
    "home_team": "Winner Match 81",
    "away_team": "Winner Match 82",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 95,
    "date": "2026-07-07",
    "time": "TBD",
    "group": "Oitavas de final",
    "stadium": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "country": "USA",
    "home_team": "Winner Match 86",
    "away_team": "Winner Match 88",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 96,
    "date": "2026-07-07",
    "time": "TBD",
    "group": "Oitavas de final",
    "stadium": "BC Place",
    "city": "Vancouver",
    "country": "Canada",
    "home_team": "Winner Match 85",
    "away_team": "Winner Match 87",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 97,
    "date": "2026-07-09",
    "time": "TBD",
    "group": "Quartas de final",
    "stadium": "Gillette Stadium",
    "city": "Boston",
    "country": "USA",
    "home_team": "Winner Match 89",
    "away_team": "Winner Match 90",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 98,
    "date": "2026-07-10",
    "time": "TBD",
    "group": "Quartas de final",
    "stadium": "SoFi Stadium",
    "city": "Los Angeles",
    "country": "USA",
    "home_team": "Winner Match 93",
    "away_team": "Winner Match 94",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 99,
    "date": "2026-07-12",
    "time": "TBD",
    "group": "Quartas de final",
    "stadium": "Hard Rock Stadium",
    "city": "Miami",
    "country": "USA",
    "home_team": "Winner Match 91",
    "away_team": "Winner Match 92",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 100,
    "date": "2026-07-12",
    "time": "TBD",
    "group": "Quartas de final",
    "stadium": "Arrowhead Stadium",
    "city": "Kansas City",
    "country": "USA",
    "home_team": "Winner Match 95",
    "away_team": "Winner Match 96",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 101,
    "date": "2026-07-14",
    "time": "TBD",
    "group": "Semifinal",
    "stadium": "AT&T Stadium",
    "city": "Dallas",
    "country": "USA",
    "home_team": "Winner Match 97",
    "away_team": "Winner Match 98",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 102,
    "date": "2026-07-15",
    "time": "TBD",
    "group": "Semifinal",
    "stadium": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "country": "USA",
    "home_team": "Winner Match 99",
    "away_team": "Winner Match 100",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 103,
    "date": "2026-07-18",
    "time": "TBD",
    "group": "Disputa 3º lugar",
    "stadium": "Hard Rock Stadium",
    "city": "Miami",
    "country": "USA",
    "home_team": "Loser Match 101",
    "away_team": "Loser Match 102",
    "score": null,
    "status": "scheduled"
  },
  {
    "id": 104,
    "date": "2026-07-19",
    "time": "TBD",
    "group": "Final",
    "stadium": "MetLife Stadium",
    "city": "East Rutherford",
    "country": "USA",
    "home_team": "Winner Match 101",
    "away_team": "Winner Match 102",
    "score": null,
    "status": "scheduled"
  }
];